// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateAuthor implements pgx.CopyFromSource.
type iteratorForCreateAuthor struct {
	rows                 []CreateAuthorParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAuthor) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAuthor) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].UserID,
		r.rows[0].Metadata,
	}, nil
}

func (r iteratorForCreateAuthor) Err() error {
	return nil
}

func (q *Queries) CreateAuthor(ctx context.Context, arg []CreateAuthorParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"authors"}, []string{"name", "user_id", "metadata"}, &iteratorForCreateAuthor{rows: arg})
}
