kafka:
  brokers:
    - "localhost:9092"

database:
  port: "5432"
  host: "localhost"
  username: "root"
  password: "root"
  database: "sh_images"
  retry:
    attempts: 5
    initial_wait: 1s
    max_wait: 15s

imgproxy:
  url: "http://localhost:9004"
  minio_url: "s3://files/"
  key: "2b33e772e9d2c041f289a5babf817bd0f4247be9d9e028cf9bf1b359d5cd6641"
  salt: "087c98d789b3d79f145c1ca33cfcd2456daad64945816881de493fe875045d10"

log_level: "debug"
service:
  expire_duration: 1h

server:
  grpc:
    host: ":8006"