// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const countPostsForTag = `-- name: CountPostsForTag :one
SELECT count(*) FROM post_tags
WHERE tag = $1
`

func (q *Queries) CountPostsForTag(ctx context.Context, tag string) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsForTag, tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTagsForPost = `-- name: GetTagsForPost :many
SELECT tag FROM post_tags
WHERE post_id = $1
`

func (q *Queries) GetTagsForPost(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getTagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
