kafka:
  brokers:
    - "localhost:9092"

database:
  port: "5432"
  host: "localhost"
  username: "root"
  password: "root"
  database: "sh_post"
  retry:
    attempts: 5
    initial_wait: 1s
    max_wait: 15s

log_level: "debug"

user:
  address: ":8081"
  backoff:
    base_delay: 500ms
    multiplier: 2
    jitter: 0.5
    max_delay: 5s
  connect_timeout: 10s

server:
  grpc:
    host: ":8083"