kafka:
  brokers:
    - "localhost:9092"

database:
  port: "5432"
  host: "localhost"
  username: "root"
  password: "root"
  database: "sh_file"
  retry:
    attempts: 5
    initial_wait: 1s
    max_wait: 15s

minio:
  endpoint: "localhost:9000"
  access_key: "GdD14n1Oxz2U5hfQhdHo"
  secret_key: "e1Peh4RLq7E4hgDW3GtV8nl4IaZjGrzDuS0WTPaB"
  use_ssl: false
  buckets:
    files: "files"
    temp: "temp-bucket"
  retry:
    attempts: 5
    initial_wait: 2s
    max_wait: 20s

log_level: "debug"
service:
  expire_duration: 1h

server:
  grpc:
    host: ":8005"
  http:
    host: ":8006"
    shutdown_timeout: 10s