// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Category struct {
	Name           string
	MetadataSchema []byte
}

type GalleryImage struct {
	ImageID int64
	PostID  *int64
	Desc    *string
}

type Post struct {
	ID       int64
	Name     string
	Desc     *string
	Owner    int64
	AuthorID *int64
}

type PostCategoryMetadatum struct {
	PostID   int64
	Category string
	Metadata []byte
}

type PostTag struct {
	PostID int64
	Tag    string
}
