// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreatePostParams struct {
	ID       int64
	Name     string
	Desc     pgtype.Text
	Owner    int64
	AuthorID pgtype.Int8
}

const getPostById = `-- name: GetPostById :one
SELECT id, name, "desc", owner, author_id FROM post
WHERE id = $1
`

func (q *Queries) GetPostById(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Owner,
		&i.AuthorID,
	)
	return i, err
}
