services:
  postgres:
    image: postgres:alpine
    networks:
      - pg-network
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=sh_user

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.0.7
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    volumes:
#      - keycloak:/opt/keycloak/data/
#    ports:
#      - "8082:8080"
#    command: start-dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    environment:
#      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - local

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - local

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "9003:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - local

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    environment:
      - IMGPROXY_USE_S3=true
      - IMGPROXY_S3_ENDPOINT=http://minio:9000
      - IMGPROXY_ALLOWED_SOURCES=s3://files
      - IMGPROXY_S3_BUCKET=images
      - IMGPROXY_S3_REGION=us-east-1
      - IMGPROXY_USE_ETAG=true
      - AWS_ACCESS_KEY_ID=1a83yMGKSWsdao695UAD # TODO env var
      - AWS_SECRET_ACCESS_KEY=wF7cGjuTXhafoSMV2Q9DmjzWevYwgY94VHUO2Vmm # TODO env var
      - AWS_REGION=local
      - IMGPROXY_KEY=2b33e772e9d2c041f289a5babf817bd0f4247be9d9e028cf9bf1b359d5cd6641
      - IMGPROXY_SALT=087c98d789b3d79f145c1ca33cfcd2456daad64945816881de493fe875045d10
    ports:
      - "9004:8080"
    networks:
      - local

volumes:
  postgres:
  keycloak:
  redis:
  minio:

networks:
  pg-network:
    external: true
  local: