// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v4.25.6
// source: api/proto/image.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetImageSizesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSizesRequest) Reset() {
	*x = GetImageSizesRequest{}
	mi := &file_api_proto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSizesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSizesRequest) ProtoMessage() {}

func (x *GetImageSizesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSizesRequest.ProtoReflect.Descriptor instead.
func (*GetImageSizesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *GetImageSizesRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetImageSizesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sizes         []*ImageSize           `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSizesResponse) Reset() {
	*x = GetImageSizesResponse{}
	mi := &file_api_proto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSizesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSizesResponse) ProtoMessage() {}

func (x *GetImageSizesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSizesResponse.ProtoReflect.Descriptor instead.
func (*GetImageSizesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageSizesResponse) GetSizes() []*ImageSize {
	if x != nil {
		return x.Sizes
	}
	return nil
}

type ImageSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PresetName    string                 `protobuf:"bytes,2,opt,name=preset_name,json=presetName,proto3" json:"preset_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSize) Reset() {
	*x = ImageSize{}
	mi := &file_api_proto_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSize) ProtoMessage() {}

func (x *ImageSize) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSize.ProtoReflect.Descriptor instead.
func (*ImageSize) Descriptor() ([]byte, []int) {
	return file_api_proto_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageSize) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageSize) GetPresetName() string {
	if x != nil {
		return x.PresetName
	}
	return ""
}

var File_api_proto_image_proto protoreflect.FileDescriptor

var file_api_proto_image_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x09, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x5a, 0x0a, 0x0c, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_image_proto_rawDescOnce sync.Once
	file_api_proto_image_proto_rawDescData = file_api_proto_image_proto_rawDesc
)

func file_api_proto_image_proto_rawDescGZIP() []byte {
	file_api_proto_image_proto_rawDescOnce.Do(func() {
		file_api_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_image_proto_rawDescData)
	})
	return file_api_proto_image_proto_rawDescData
}

var file_api_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_image_proto_goTypes = []any{
	(*GetImageSizesRequest)(nil),  // 0: proto.GetImageSizesRequest
	(*GetImageSizesResponse)(nil), // 1: proto.GetImageSizesResponse
	(*ImageSize)(nil),             // 2: proto.ImageSize
}
var file_api_proto_image_proto_depIdxs = []int32{
	2, // 0: proto.GetImageSizesResponse.sizes:type_name -> proto.ImageSize
	0, // 1: proto.ImageService.GetImageSizes:input_type -> proto.GetImageSizesRequest
	1, // 2: proto.ImageService.GetImageSizes:output_type -> proto.GetImageSizesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_image_proto_init() }
func file_api_proto_image_proto_init() {
	if File_api_proto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_image_proto_goTypes,
		DependencyIndexes: file_api_proto_image_proto_depIdxs,
		MessageInfos:      file_api_proto_image_proto_msgTypes,
	}.Build()
	File_api_proto_image_proto = out.File
	file_api_proto_image_proto_rawDesc = nil
	file_api_proto_image_proto_goTypes = nil
	file_api_proto_image_proto_depIdxs = nil
}
