// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v4.25.6
// source: api/proto/tag.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoryVarsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Values        []byte                 `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryVarsParams) Reset() {
	*x = CreateCategoryVarsParams{}
	mi := &file_api_proto_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryVarsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryVarsParams) ProtoMessage() {}

func (x *CreateCategoryVarsParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryVarsParams.ProtoReflect.Descriptor instead.
func (*CreateCategoryVarsParams) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryVarsParams) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCategoryVarsParams) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateCategoryVarsParams) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetCategVarsByPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategVarsByPostRequest) Reset() {
	*x = GetCategVarsByPostRequest{}
	mi := &file_api_proto_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategVarsByPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategVarsByPostRequest) ProtoMessage() {}

func (x *GetCategVarsByPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategVarsByPostRequest.ProtoReflect.Descriptor instead.
func (*GetCategVarsByPostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategVarsByPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CategoryVars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Vars          []byte                 `protobuf:"bytes,3,opt,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryVars) Reset() {
	*x = CategoryVars{}
	mi := &file_api_proto_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryVars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryVars) ProtoMessage() {}

func (x *CategoryVars) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryVars.ProtoReflect.Descriptor instead.
func (*CategoryVars) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryVars) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CategoryVars) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryVars) GetVars() []byte {
	if x != nil {
		return x.Vars
	}
	return nil
}

type CategVarsByPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CategoryVars        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategVarsByPostResponse) Reset() {
	*x = CategVarsByPostResponse{}
	mi := &file_api_proto_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategVarsByPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategVarsByPostResponse) ProtoMessage() {}

func (x *CategVarsByPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategVarsByPostResponse.ProtoReflect.Descriptor instead.
func (*CategVarsByPostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_proto_rawDescGZIP(), []int{3}
}

func (x *CategVarsByPostResponse) GetItems() []*CategoryVars {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_tag_proto protoreflect.FileDescriptor

var file_api_proto_tag_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x56, 0x61, 0x72, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x56, 0x61,
	0x72, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x56, 0x61, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x76, 0x61, 0x72,
	0x73, 0x22, 0x44, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x56, 0x61, 0x72, 0x73, 0x42, 0x79,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x56, 0x61, 0x72, 0x73,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xb7, 0x01, 0x0a, 0x0a, 0x54, 0x61, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x56, 0x61, 0x72, 0x73, 0x12, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x56, 0x61, 0x72, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x56, 0x61, 0x72, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x56, 0x61,
	0x72, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x56, 0x61, 0x72,
	0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4d, 0x4b, 0x4b, 0x4c, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x2d,
	0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_tag_proto_rawDescOnce sync.Once
	file_api_proto_tag_proto_rawDescData = file_api_proto_tag_proto_rawDesc
)

func file_api_proto_tag_proto_rawDescGZIP() []byte {
	file_api_proto_tag_proto_rawDescOnce.Do(func() {
		file_api_proto_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_tag_proto_rawDescData)
	})
	return file_api_proto_tag_proto_rawDescData
}

var file_api_proto_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_tag_proto_goTypes = []any{
	(*CreateCategoryVarsParams)(nil),  // 0: proto.CreateCategoryVarsParams
	(*GetCategVarsByPostRequest)(nil), // 1: proto.GetCategVarsByPostRequest
	(*CategoryVars)(nil),              // 2: proto.CategoryVars
	(*CategVarsByPostResponse)(nil),   // 3: proto.CategVarsByPostResponse
	(*emptypb.Empty)(nil),             // 4: google.protobuf.Empty
}
var file_api_proto_tag_proto_depIdxs = []int32{
	2, // 0: proto.CategVarsByPostResponse.items:type_name -> proto.CategoryVars
	0, // 1: proto.TagService.CreateCategoryVars:input_type -> proto.CreateCategoryVarsParams
	1, // 2: proto.TagService.GetCategVarsByPost:input_type -> proto.GetCategVarsByPostRequest
	4, // 3: proto.TagService.CreateCategoryVars:output_type -> google.protobuf.Empty
	3, // 4: proto.TagService.GetCategVarsByPost:output_type -> proto.CategVarsByPostResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_tag_proto_init() }
func file_api_proto_tag_proto_init() {
	if File_api_proto_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tag_proto_goTypes,
		DependencyIndexes: file_api_proto_tag_proto_depIdxs,
		MessageInfos:      file_api_proto_tag_proto_msgTypes,
	}.Build()
	File_api_proto_tag_proto = out.File
	file_api_proto_tag_proto_rawDesc = nil
	file_api_proto_tag_proto_goTypes = nil
	file_api_proto_tag_proto_depIdxs = nil
}
