// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	Hash        string
	FileSize    int32
	ContentType string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TmpFile struct {
	StoreKey           string
	FileName           string
	ContentType        string
	Status             string
	ErrorReason        *string
	ProcessingAttempts pgtype.Int4
	FinalHash          *string
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
