// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO tmp_file (file_hash, file_name, content_type, file_size, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING file_hash, file_name, content_type, file_size, expires_at, created_at, updated_at
`

type CreateFileParams struct {
	FileHash    string
	FileName    string
	ContentType string
	FileSize    int64
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (TmpFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FileHash,
		arg.FileName,
		arg.ContentType,
		arg.FileSize,
		arg.ExpiresAt,
	)
	var i TmpFile
	err := row.Scan(
		&i.FileHash,
		&i.FileName,
		&i.ContentType,
		&i.FileSize,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT file_hash, file_name, content_type, file_size, expires_at, created_at, updated_at FROM tmp_file
WHERE file_hash = $1
`

func (q *Queries) GetFileByHash(ctx context.Context, fileHash string) (TmpFile, error) {
	row := q.db.QueryRow(ctx, getFileByHash, fileHash)
	var i TmpFile
	err := row.Scan(
		&i.FileHash,
		&i.FileName,
		&i.ContentType,
		&i.FileSize,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredFiles = `-- name: ListExpiredFiles :many
SELECT file_hash, expires_at
FROM tmp_file
WHERE expires_at < NOW()
`

type ListExpiredFilesRow struct {
	FileHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListExpiredFiles(ctx context.Context) ([]ListExpiredFilesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredFilesRow
	for rows.Next() {
		var i ListExpiredFilesRow
		if err := rows.Scan(&i.FileHash, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
