// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttachedFile struct {
	Hash      *string
	TempID    pgtype.UUID
	PostID    int64
	Name      string
	FileSize  int32
	Downloads int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Category struct {
	Name           string
	MetadataSchema []byte
}

type GalleryImage struct {
	PostID *int64
	FileID string
	Order  int16
	Desc   *string
}

type Post struct {
	ID        int64
	Name      string
	Desc      *string
	Owner     int64
	AuthorID  *int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PostCategoryMetadatum struct {
	PostID   int64
	Category string
	Metadata []byte
}

type PostTag struct {
	PostID int64
	Tag    string
}
